### ISSUE TITLE
Calling `GameObject.destory()` from within update causes crash

### ISSUE THREAD

**Issue by Olliebrown** [samme/phaser-plugin-update#2]
### Description
Ran into an interesting bug triggered by this plugin for the following situation:
- Using the phaser-plugin-update scene plugin
- Having multiple game objects with active update functions
- Deleting one of those objects by calling 'destroy()' inside of the object's update function
- An attempt will be made to call 'update' on an undefined object that causes the game to crash

I have reproduced this in both MacOS and Windows in Chrome and Firefox.  The problem stems from the use of Phaser.Structs.Set as the main container.  The implementation of `iterateLocal()` for the set ends up reading the 'length' of the internal array to a local variable before looping through the array and calling 'update' on each item.  Somehow (I'm not quite sure how) a game object can wind up getting deleted and changed to 'undefined' and the length can decrease WHILE that loop is happening.  This causes the loop to read one object past the end and it tries to call 'update' on an undefined object.

### Code to Reproduce
Here is a minimal code-pen example that reliably triggers the error:
- https://codepen.io/Olliebrown/pen/qBBYQaW
- Press '+' to add 20 objects to the scene with active update() functions
- Then press '-' to delete those objects with their 'destroy()' method from inside their update
- This will trigger the error and cause a crash

### Workaround
The only workaround I've found is to not use the Phaser Set class but instead to use my own array.  This affords the opportunity to ensure the object is defined before calling update and to avoid trying to call it on an undefined object.

It seems a bit dubious to call 'destroy()' from within an update() anyways but the folks in the Phaser discord said that it shouldn't be an issue in general.

**Comment by samme** [comment]
Fixed, thanks. https://codepen.io/samme/pen/XWWYEqG
